SRC = Name.swift Pdf.swift Satellite.swift StarSystem.swift main.swift Dice.swift Planet.swift Star.swift

StarSystems: $(SRC)
	xcrun -sdk macosx swiftc -o StarSystems -O -whole-module-optimization $(SRC)
