line_length: 200
identifier_name:
  min_length: # only min_length
    error:  1 # only error
  excluded:
    - x
    - y
    - id
disabled_rules:
  - trailing_whitespace 
  - function_body_length
  - cyclomatic_complexity
  - type_body_length
  - file_length

